cms/urls.py
from django.urls import path

from cms.views import PlaceCreateView, PlaceDetailView, PlaceListView


app_name = 'cms'

urlpatterns = [
    path('', PlaceListView.as_view(), name='place_list'),
    path('places/new', PlaceCreateView.as_view(), name='place_create'),
    path('places/<int:pk>', PlaceDetailView.as_view(), name='place_detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cms.urls')),
]

from django.conf import settings
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/models.py
from django.contrib.gis.db import models
from django.urls import reverse


class Place(models.Model):
    picture = models.ImageField(upload_to='images')
    details = models.TextField()
    size = models.DecimalField(max_digits=9, decimal_places=2)
    price = models.DecimalField(max_digits=15, decimal_places=2)
    address = models.CharField(max_length=255)
    location = models.PointField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse('cms:place_detail', args=[str(self.id)])

cms/forms.py
from django import forms
from django.contrib.gis.geos import Point

from cms.models import Place
from cms.services import address_to_point


class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = '__all__'

    def clean(self):
        cleaned_data = super().clean()
        address = cleaned_data.get('address')

        try:
            _location = address_to_point(address)
            location = Point(*_location)
            self.cleaned_data['location'] = location
        except Exception as e:
            self.add_error('address', str(e))

cms/views.py
from django.contrib.gis.geos import Point
from django.contrib.gis.db.models.functions import Distance
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, ListView

from cms.forms import PlaceForm
from cms.models import Place


class PlaceCreateView(CreateView):
    model = Place
    form_class = PlaceForm


class PlaceDetailView(DetailView):
    model = Place


#class PlaceListView(ListView, FormMixin):
class PlaceListView(ListView):
    model = Place
    #form_class = myFormDaVidaAi

    #def form_valid(self, form):
    #    return url(com o point)
    #    return HttpResponseRedirect(self.get_success_url())

    def get_queryset(self):
        qs = super().get_queryset()
        GET = self.request.GET
        lat, lng = GET.get('lat'), GET.get('lng')
        if lat and lng:
            point = Point(float(lat), float(lng), srid=32140)
            distance = Distance('location', point)
            return qs.annotate(distance=distance).order_by('distance')
        return qs

cms/templates/cms/place_detail.html
{% extends 'core/base.html' %}
{% load humanize %}
{% block content %}
<p>
  <a href="{% url 'cms:place_list' %}">Back to place list.</a>
</p>
<h2>Place details</h2>
<img src="{{ object.picture.url }}" alt="Picture" width="100%">
<p class="details">{{ object.details }}</p>
<p>{{ object.address}}</p>
<table>
  <tbody>
    <tr>
      <th>Price</th>
      <td>${{ object.price|intcomma }}</td>
    </tr>
    <tr>
      <th>Size</th>
      <td>{{ object.size }}m<sup>2</sup></td>
    </tr>
  </tbody>
</table>
{% endblock %}

cms/templates/cms/place_form.html
{% extends 'core/base.html' %}
{% block content %}
<h2>Add a new place.</h2>
<p>
    <a href="{% url 'cms:place_list' %}">Back to place list.</a>
</p>
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
{% for field in form %}
{% if field.name != 'location' %}
  <div class="form-item">
  {{ field.label_tag }}
  {{ field }}
  </div>
{% endif %}
{% endfor %}
    {% if form.errors %}
    <div class="errors">
        <p>
            {% for field in form %}
            {% if field.errors %}{{ field.label }} - {{ field.errors|striptags }} {% endif %}
            {% endfor %}
        </p>
    </div>
    {% endif %}
  <div class="form-item">
    <input type="submit" value="Create" class="success" name="">
  </div>
</form>
{% endblock %}

cms/templates/cms/place_list.html
{% extends 'core/base.html' %}
{% load imagekit %}
{% block content %}
<ul class='list'>
  <li>
    <a href="{% url 'cms:place_create' %}" title="Add a new place.">➕</a>
  </li>
{% for obj in object_list %}
  <li>
    <a href="{{ obj.get_absolute_url }}">
    {% thumbnail "200x200" obj.picture %}
    </a>
    <p>
    {{ obj.details | truncatechars:30 }}
    </p>
  </li>
{% endfor %}
</ul>
{% endblock %}

core/templates/core/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <title>Find your place {% block title %}{% endblock %}</title>
  <meta name="description" content="Rent your place here.">
  <link href="https://fonts.googleapis.com/css?family=Sacramento" rel="stylesheet">
  <link href="{% static 'css/style.css'  %}" rel="stylesheet" />
</head>
<body>
  <header>
    <div>
      <h1>Find your place</h1>
    </div>
  </header>
  <section>
    <section>
      {% block content %}{% endblock %}
    </section>
  </section>
</body>
</html>